version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    docker:
      - image: cimg/android:2023.10
        environment:
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk

    steps:
      # Checkout the code
      - checkout

      # Update package manager and install dependencies
      - run:
          name: Update and install OpenJDK 17
          command: |
            sudo apt-get update
            sudo apt-get install -y openjdk-17-jdk

      # Install Gradle if necessary (optional, as the Docker image might already include it)
      - run:
          name: Install Gradle
          command: |
            wget https://services.gradle.org/distributions/gradle-8.7-all.zip
            unzip gradle-8.7-all.zip
            sudo mv gradle-8.7 /opt/gradle
            sudo ln -s /opt/gradle/bin/gradle /usr/local/bin/gradle

      # Ensure gradle wrapper has execute permissions
      - run:
          name: Chmod permissions for gradlew
          command: sudo chmod +x ./gradlew

      # Download dependencies using Gradle
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      # Cache the Gradle build cache
      - save_cache:
          key: android-orb-v1-{{ epoch }}
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper

      # Build the project
      - run:
          name: Run Build
          command: ./gradlew build

      # Store build reports
      - store_artifacts:
          path: app/build/reports
          destination: reports

      # Run Lint and tests
      - run:
          name: Run Tests
          command: ./gradlew lint test

      # Store test results
      - store_test_results:
          path: app/build/test-results

      # Store APK artifacts
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: artifact-file

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
